### ISSUE TITLE
Celery's rdb is not compatible with pdbpp > 0.10

### ISSUE THREAD

**Issue by Hugo-C** [bretello/pdbpp#60]
Hello,

The Celery project has a remote debbuger called [rdb](https://github.com/celery/celery/blob/main/celery/contrib/rdb.py). It was working fine with `pdbpp` up to `0.10.3`. `0.11.5` (the next available release on pypi), breaks with the following exception:

> Traceback (most recent call last):
  File "/path/to/src/replicate_rdb_init_error/main.py", line 8, in <module>
    main()
    ~~~~^^
  File "/path/to/src/replicate_rdb_init_error/main.py", line 4, in main
    rdb.set_trace()
    ~~~~~~~~~~~~~^^
  File "/path/to/lib/python3.13/site-packages/celery/contrib/rdb.py", line 187, in set_trace
    return debugger().set_trace(frame)
           ~~~~~~~~^^
  File "/path/to/lib/python3.13/site-packages/celery/contrib/rdb.py", line 179, in debugger
    rdb = _current[0] = Rdb()
                        ~~~^^
  File "/path/to/lib/python3.13/site-packages/pdbpp.py", line 279, in __call__
    obj.__init__(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: Rdb.__init__() got an unexpected keyword argument 'start_filename'

A minimal reproducible example is available here: https://github.com/Hugo-C/replicate-rdb-init-error
It boils down to:
```python
from celery.contrib import rdb

def main():
    rdb.set_trace()
    print('hello')
```

Is it something you consider like a bug on your side ? Or would you rather see it fixed in Celery ?

**Comment by bretello** [comment]
Thanks for the detailed report. It looks like the culprit is here:

https://github.com/bretello/pdbpp/blob/5694940c7001446649abfa969a9e1033c6c4aabe/src/pdbpp.py?plain=1#L283-L294

the `PdbMeta` class attempts to reuse existing Pdb (`pdbpp.Pdb`) instances when possible.

When subclassing Pdb (`class Rdb(Pdb)`) with pdbpp installed and enabled, this breaks calling `set_trace`.

I have a tentative fix for this here: https://github.com/bretello/pdbpp/pull/61

This basically breaks reuse of existing instances for Pdb subclasses and causes some tests to fail ( `testing/test_pdb.py::test_config_gets_start_filename`), so I need a bit more time to figure out if there's a better way to do this.
